import Google from "@auth/core/providers/google";
import { convexAuth } from "@convex-dev/auth/server";

/**
 * Convex Auth wiring. Google is the only provider in the MVP.
 *
 * Required env vars (set via `pnpm exec convex env set ...` for cloud deploys):
 *   AUTH_GOOGLE_ID
 *   AUTH_GOOGLE_SECRET
 *   JWT_PRIVATE_KEY    (generated by `@convex-dev/auth`'s init script)
 *   JWKS               (likewise)
 *   SITE_URL           (e.g. http://localhost:3000)
 */
export const { auth, signIn, signOut, store, isAuthenticated } = convexAuth({
	providers: [Google],
});
